server:
  port: 8080

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/testcopy?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: 马赛克
      password: 马赛克
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver



  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

mybatis:
  type-aliases-package: cn.yonyong.pojo
  mapper-locations: classpath:mapper/*.xml